/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IOneSplitViewInterface extends ethers.utils.Interface {
  functions: {
    "getExpectedReturn(address,address,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getExpectedReturn",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getExpectedReturn",
    data: BytesLike
  ): Result;

  events: {};
}

export class IOneSplitView extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IOneSplitViewInterface;

  functions: {
    getExpectedReturn(
      fromToken: string,
      toToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      returnAmount: BigNumber;
      distribution: BigNumber[];
      0: BigNumber;
      1: BigNumber[];
    }>;

    "getExpectedReturn(address,address,uint256,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      returnAmount: BigNumber;
      distribution: BigNumber[];
      0: BigNumber;
      1: BigNumber[];
    }>;
  };

  getExpectedReturn(
    fromToken: string,
    toToken: string,
    amount: BigNumberish,
    parts: BigNumberish,
    flags: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    returnAmount: BigNumber;
    distribution: BigNumber[];
    0: BigNumber;
    1: BigNumber[];
  }>;

  "getExpectedReturn(address,address,uint256,uint256,uint256)"(
    fromToken: string,
    toToken: string,
    amount: BigNumberish,
    parts: BigNumberish,
    flags: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    returnAmount: BigNumber;
    distribution: BigNumber[];
    0: BigNumber;
    1: BigNumber[];
  }>;

  callStatic: {
    getExpectedReturn(
      fromToken: string,
      toToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      returnAmount: BigNumber;
      distribution: BigNumber[];
      0: BigNumber;
      1: BigNumber[];
    }>;

    "getExpectedReturn(address,address,uint256,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      returnAmount: BigNumber;
      distribution: BigNumber[];
      0: BigNumber;
      1: BigNumber[];
    }>;
  };

  filters: {};

  estimateGas: {
    getExpectedReturn(
      fromToken: string,
      toToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getExpectedReturn(address,address,uint256,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getExpectedReturn(
      fromToken: string,
      toToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getExpectedReturn(address,address,uint256,uint256,uint256)"(
      fromToken: string,
      toToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
