/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface LpAppraisorInterface extends ethers.utils.Interface {
  functions: {
    "acceptGovernance()": FunctionFragment;
    "appraise(uint256)": FunctionFragment;
    "curve_A()": FunctionFragment;
    "curve_B2()": FunctionFragment;
    "governance()": FunctionFragment;
    "lpToken()": FunctionFragment;
    "newGovernance()": FunctionFragment;
    "setCurve(uint256,uint256)": FunctionFragment;
    "setGovernance(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "appraise",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "curve_A", values?: undefined): string;
  encodeFunctionData(functionFragment: "curve_B2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "newGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCurve",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "appraise", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "curve_A", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "curve_B2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "newGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCurve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike
  ): Result;

  events: {
    "GovernanceTransferred(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GovernanceTransferred"): EventFragment;
}

export class LpAppraisor extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LpAppraisorInterface;

  functions: {
    acceptGovernance(overrides?: Overrides): Promise<ContractTransaction>;

    "acceptGovernance()"(overrides?: Overrides): Promise<ContractTransaction>;

    appraise(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      _value: BigNumber;
      0: BigNumber;
    }>;

    "appraise(uint256)"(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      _value: BigNumber;
      0: BigNumber;
    }>;

    curve_A(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "curve_A()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    curve_B2(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "curve_B2()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    governance(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "governance()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    lpToken(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "lpToken()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    newGovernance(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "newGovernance()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setCurve(
      _curve_A: BigNumberish,
      _curve_B: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCurve(uint256,uint256)"(
      _curve_A: BigNumberish,
      _curve_B: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  acceptGovernance(overrides?: Overrides): Promise<ContractTransaction>;

  "acceptGovernance()"(overrides?: Overrides): Promise<ContractTransaction>;

  appraise(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "appraise(uint256)"(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  curve_A(overrides?: CallOverrides): Promise<BigNumber>;

  "curve_A()"(overrides?: CallOverrides): Promise<BigNumber>;

  curve_B2(overrides?: CallOverrides): Promise<BigNumber>;

  "curve_B2()"(overrides?: CallOverrides): Promise<BigNumber>;

  governance(overrides?: CallOverrides): Promise<string>;

  "governance()"(overrides?: CallOverrides): Promise<string>;

  lpToken(overrides?: CallOverrides): Promise<string>;

  "lpToken()"(overrides?: CallOverrides): Promise<string>;

  newGovernance(overrides?: CallOverrides): Promise<string>;

  "newGovernance()"(overrides?: CallOverrides): Promise<string>;

  setCurve(
    _curve_A: BigNumberish,
    _curve_B: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setCurve(uint256,uint256)"(
    _curve_A: BigNumberish,
    _curve_B: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setGovernance(
    _governance: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setGovernance(address)"(
    _governance: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptGovernance(overrides?: CallOverrides): Promise<void>;

    "acceptGovernance()"(overrides?: CallOverrides): Promise<void>;

    appraise(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "appraise(uint256)"(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    curve_A(overrides?: CallOverrides): Promise<BigNumber>;

    "curve_A()"(overrides?: CallOverrides): Promise<BigNumber>;

    curve_B2(overrides?: CallOverrides): Promise<BigNumber>;

    "curve_B2()"(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<string>;

    "governance()"(overrides?: CallOverrides): Promise<string>;

    lpToken(overrides?: CallOverrides): Promise<string>;

    "lpToken()"(overrides?: CallOverrides): Promise<string>;

    newGovernance(overrides?: CallOverrides): Promise<string>;

    "newGovernance()"(overrides?: CallOverrides): Promise<string>;

    setCurve(
      _curve_A: BigNumberish,
      _curve_B: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setCurve(uint256,uint256)"(
      _curve_A: BigNumberish,
      _curve_B: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setGovernance(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    GovernanceTransferred(_newGovernance: null): EventFilter;
  };

  estimateGas: {
    acceptGovernance(overrides?: Overrides): Promise<BigNumber>;

    "acceptGovernance()"(overrides?: Overrides): Promise<BigNumber>;

    appraise(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "appraise(uint256)"(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    curve_A(overrides?: CallOverrides): Promise<BigNumber>;

    "curve_A()"(overrides?: CallOverrides): Promise<BigNumber>;

    curve_B2(overrides?: CallOverrides): Promise<BigNumber>;

    "curve_B2()"(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    "governance()"(overrides?: CallOverrides): Promise<BigNumber>;

    lpToken(overrides?: CallOverrides): Promise<BigNumber>;

    "lpToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    newGovernance(overrides?: CallOverrides): Promise<BigNumber>;

    "newGovernance()"(overrides?: CallOverrides): Promise<BigNumber>;

    setCurve(
      _curve_A: BigNumberish,
      _curve_B: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setCurve(uint256,uint256)"(
      _curve_A: BigNumberish,
      _curve_B: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptGovernance(overrides?: Overrides): Promise<PopulatedTransaction>;

    "acceptGovernance()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    appraise(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "appraise(uint256)"(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    curve_A(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "curve_A()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    curve_B2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "curve_B2()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "governance()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lpToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lpToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newGovernance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "newGovernance()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setCurve(
      _curve_A: BigNumberish,
      _curve_B: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCurve(uint256,uint256)"(
      _curve_A: BigNumberish,
      _curve_B: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
