/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { MockProduct } from "./MockProduct";

export class MockProductFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(_registry: string, overrides?: Overrides): Promise<MockProduct> {
    return super.deploy(_registry, overrides || {}) as Promise<MockProduct>;
  }
  getDeployTransaction(
    _registry: string,
    overrides?: Overrides
  ): TransactionRequest {
    return super.getDeployTransaction(_registry, overrides || {});
  }
  attach(address: string): MockProduct {
    return super.attach(address) as MockProduct;
  }
  connect(signer: Signer): MockProductFactory {
    return super.connect(signer) as MockProductFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockProduct {
    return new Contract(address, _abi, signerOrProvider) as MockProduct;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_registry",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "policy",
        type: "address",
      },
    ],
    name: "PolicyCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "policy",
        type: "address",
      },
    ],
    name: "PolicyDeleted",
    type: "event",
  },
  {
    inputs: [],
    name: "createPolicy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_policy",
        type: "address",
      },
    ],
    name: "deletePolicy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "registry",
    outputs: [
      {
        internalType: "contract Registry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161030f38038061030f83398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610082565b600060208284031215610065578081fd5b81516001600160a01b038116811461007b578182fd5b9392505050565b61027e806100916000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80635fabdf7c146100465780637b1039991461005b578063a91a0ca314610079575b600080fd5b6100596100543660046101f8565b610081565b005b61006361011d565b6040516100709190610234565b60405180910390f35b61006361012c565b600054604051633c69c6c160e11b81526001600160a01b03909116906378d38d82906100b1908490600401610234565b600060405180830381600087803b1580156100cb57600080fd5b505af11580156100df573d6000803e3d6000fd5b505050507f9a3ff41a17fac67cf81d676a8a3fe47e718869470cfb2c6b452ac27996d63267816040516101129190610234565b60405180910390a150565b6000546001600160a01b031681565b600080424340604051602001610143929190610226565b60408051601f1981840301815290829052805160209091012060005463b84ef08160e01b83529092506001600160a01b03169063b84ef0819061018a908490600401610234565b600060405180830381600087803b1580156101a457600080fd5b505af11580156101b8573d6000803e3d6000fd5b505050507f2f111d8a56aa0ad671b0442ae028827407496656571a697781157db90a03ae14816040516101eb9190610234565b60405180910390a1905090565b600060208284031215610209578081fd5b81356001600160a01b038116811461021f578182fd5b9392505050565b918252602082015260400190565b6001600160a01b039190911681526020019056fea264697066735822122023dfdc1b2047837ae59094df451903e7c6bfbe7d7cc4776c3f8c7e6326f920e864736f6c63430008000033";
