/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { MockErc721Appraiser } from "./MockErc721Appraiser";

export class MockErc721AppraiserFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _contract: string,
    overrides?: Overrides
  ): Promise<MockErc721Appraiser> {
    return super.deploy(
      _contract,
      overrides || {}
    ) as Promise<MockErc721Appraiser>;
  }
  getDeployTransaction(
    _contract: string,
    overrides?: Overrides
  ): TransactionRequest {
    return super.getDeployTransaction(_contract, overrides || {});
  }
  attach(address: string): MockErc721Appraiser {
    return super.attach(address) as MockErc721Appraiser;
  }
  connect(signer: Signer): MockErc721AppraiserFactory {
    return super.connect(signer) as MockErc721AppraiserFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockErc721Appraiser {
    return new Contract(address, _abi, signerOrProvider) as MockErc721Appraiser;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "appraise",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nftContract",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161024a38038061024a83398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610082565b600060208284031215610065578081fd5b81516001600160a01b038116811461007b578182fd5b9392505050565b6101b9806100916000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063d56d229d1461003b578063f56ff92814610059575b600080fd5b610043610079565b6040516100509190610159565b60405180910390f35b61006c610067366004610129565b610095565b604051610050919061017a565b60005473ffffffffffffffffffffffffffffffffffffffff1681565b60008054604051635e383d2160e01b815273ffffffffffffffffffffffffffffffffffffffff90911690635e383d21906100d390859060040161017a565b60206040518083038186803b1580156100eb57600080fd5b505afa1580156100ff573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101239190610141565b92915050565b60006020828403121561013a578081fd5b5035919050565b600060208284031215610152578081fd5b5051919050565b73ffffffffffffffffffffffffffffffffffffffff91909116815260200190565b9081526020019056fea2646970667358221220924272bfd0a5778c361ae5640ca7e4d77e83fec6fe5f7a593be221ac8f50aae064736f6c63430008000033";
